import { test, expect } from '@playwright/test'

const input = page => page.getByRole('textbox', { name: 'JSON 输入', exact: true })
const output = page => page.getByRole('textbox', { name: '处理结果', exact: true })
async function go(page, path) { await page.goto(`./#/${path}`); await expect(page.locator('.tool-workspace')).toBeVisible() }
async function tool(page, name) {
  await page.keyboard.press('Control+k')
  await page.getByRole('combobox', { name: '搜索工具或当前操作' }).fill(name)
  await page.locator('.command-results').getByRole('option').filter({ hasText: name }).first().click()
}
async function complete(page) { await expect(page.locator('.workspace-status')).toContainText('处理完成') }

test('JSON exact data, safe rendering, download, stale result and tree queries', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message))
  await go(page, 'json')
  await input(page).fill('{"id":9223372036854775807,"html":"<b>hello</b>","a.b":[false]}')
  await page.getByRole('button', { name: '格式化', exact: true }).click(); await complete(page)
  await expect(output(page)).toContainText('9223372036854775807')
  await expect(output(page)).toContainText('<b>hello</b>')
  await expect(output(page).locator('b')).toHaveCount(0)
  const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: '下载', exact: true }).click()])
  const stream = await download.createReadStream(); const chunks = []; for await (const chunk of stream) chunks.push(chunk)
  expect(Buffer.concat(chunks).toString()).toContain('9223372036854775807')
  await page.getByRole('button', { name: '树视图', exact: true }).click()
  await expect(page.locator('.tree-panel')).toContainText('9223372036854775807')
  await page.getByLabel('路径查询', { exact: true }).fill('$["a.b"][0]')
  await expect(page.getByRole('button', { name: '复制', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '查询', exact: true }).click(); await complete(page)
  await expect(output(page)).toContainText('false')
  await input(page).fill('{"invalid":}')
  await page.getByRole('button', { name: '格式化', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('第 1 行')
  await expect(page.getByRole('button', { name: '复制', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '定位错误' }).click()
  await expect(input(page)).toBeFocused()
  expect(errors).toEqual([])
})

test('drafts, undo, keyboard commands and focus layout survive tool switching', async ({ page }) => {
  await go(page, 'json')
  await input(page).fill('{"draft":"你好 🌍"}')
  await input(page).press('Control+Enter'); await complete(page)
  await tool(page, 'Base64')
  await tool(page, 'JSON')
  await expect(input(page)).toContainText('你好 🌍')
  await page.getByRole('button', { name: '清空', exact: true }).click()
  await expect(page.locator('.workspace-status')).toContainText('0 字符')
  await page.getByRole('button', { name: '恢复', exact: true }).click()
  await expect(input(page)).toContainText('你好 🌍')
  await page.getByRole('button', { name: '收起导航', exact: true }).click()
  const bounds = await page.locator('#json-input .editor-host').boundingBox()
  expect(bounds.width).toBeGreaterThanOrEqual(560); expect(bounds.height).toBeGreaterThanOrEqual(480)
  await page.getByRole('separator').focus(); await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('separator')).toHaveAttribute('aria-valuenow', '52')
  await page.getByRole('button', { name: '专注模式' }).click()
  await page.keyboard.press('Escape')
  await expect(page.locator('.tool-workspace')).not.toHaveClass(/is-focused/)
  await page.getByRole('button', { name: '放大输入区' }).click()
  await expect(page.locator('#json-output')).toBeHidden()
  await page.getByRole('button', { name: '还原输入区' }).click()
  await expect(page.locator('#json-output')).toBeVisible()
  await page.reload()
  await expect(page.locator('.workspace-status')).toContainText('0 字符')
})

test('Base64 modes, transfer confirmation and restore displaced JSON draft', async ({ page }) => {
  await go(page, 'json'); await input(page).fill('{"original":true}')
  await tool(page, 'Base64')
  const editor = page.getByRole('textbox', { name: 'Base64 输入' })
  await editor.fill('{"id":9223372036854775807,"msg":"你好 🌍"}')
  await page.locator('.workspace-toolbar > .btn-primary').click(); await complete(page)
  await page.getByRole('button', { name: '结果用作反向输入' }).click()
  await page.locator('.workspace-toolbar > .btn-primary').click(); await complete(page)
  await expect(output(page)).toContainText('你好 🌍')
  await page.getByRole('combobox', { name: '发送结果到工具' }).selectOption('json')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: '保留旧稿，取消' }).click()
  await page.getByRole('combobox', { name: '发送结果到工具' }).selectOption('json')
  await page.getByRole('button', { name: '替换并打开' }).click()
  await expect(input(page)).toContainText('9223372036854775807')
  await page.getByRole('button', { name: '格式化', exact: true }).click(); await complete(page)
  await page.getByRole('button', { name: '恢复', exact: true }).click()
  await expect(input(page)).toContainText('original')
})

test('YAML exact numeric formatting, conversion, multiple documents and templates', async ({ page }) => {
  await go(page, 'yaml')
  const editor = page.getByRole('textbox', { name: 'YAML 输入' })
  await editor.fill('# comment\nid: 9223372036854775807\nf: 1.1234567890123456789')
  await page.getByRole('button', { name: '格式化', exact: true }).click(); await complete(page)
  await expect(output(page)).toContainText('# comment')
  await expect(output(page)).toContainText('1.1234567890123456789')
  await page.getByRole('button', { name: '转 JSON', exact: true }).click(); await complete(page)
  await expect(output(page)).toContainText('9223372036854775807')
  await page.getByText('模板与使用说明', { exact: true }).click()
  await page.getByRole('button', { name: 'Kubernetes', exact: true }).click()
  await page.getByRole('button', { name: '仅校验', exact: true }).click(); await complete(page)
  await expect(output(page)).toContainText('2 个文档')
})

test('Diff displays changes, handles exact JSON values and rejects duplicate keys', async ({ page }) => {
  await go(page, 'diff')
  await page.getByRole('textbox', { name: '原始内容', exact: true }).fill('{"id":9223372036854775807}')
  await page.getByRole('textbox', { name: '修改后内容', exact: true }).fill('{"id":9223372036854775808}')
  await page.getByRole('combobox', { name: '比较模式' }).selectOption('json')
  await page.getByRole('button', { name: '比较', exact: true }).click(); await complete(page)
  await expect(page.locator('.diff-block.removed')).toContainText('9223372036854775807')
  await expect(page.locator('.diff-block.added')).toContainText('9223372036854775808')
  await page.getByRole('button', { name: '下一处', exact: true }).click()
  await expect(page.locator('.diff-block.active')).toBeFocused()
  await page.getByRole('textbox', { name: '修改后内容', exact: true }).fill('{"id":1,"id":2}')
  await page.getByRole('button', { name: '比较', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('重复键')
})

test('mobile workspace has input/result tabs without horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await go(page, 'json')
  await input(page).fill('{"mobile":true}')
  await page.getByRole('button', { name: '格式化', exact: true }).click(); await complete(page)
  await expect(output(page)).toBeVisible(); await expect(input(page)).toBeHidden()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('tab', { name: '输入', exact: true }).click()
  await expect(input(page)).toBeVisible()
  await page.getByRole('button', { name: '打开导航' }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: '打开导航' })).toBeFocused()
})

test('editor supports composition, search and undo across navigation', async ({ page }) => {
  await go(page, 'json')
  await input(page).fill('{"text":"')
  await input(page).press('Control+End')
  const cdp = await page.context().newCDPSession(page)
  await cdp.send('Input.imeSetComposition', { text: '你好', selectionStart: 2, selectionEnd: 2 })
  await cdp.send('Input.insertText', { text: '你好' })
  await page.keyboard.insertText('🌍"}')
  await input(page).press('Control+Enter'); await complete(page)
  await expect(output(page)).toContainText('你好🌍')
  await page.locator('#json-input').getByRole('button', { name: '查找', exact: true }).click()
  await page.locator('#json-input .cm-search input[name="search"]').fill('你好')
  await expect(page.locator('#json-input .cm-searchMatch')).toHaveCount(1)
  await page.keyboard.press('Escape')
  await input(page).press('Control+End')
  await page.keyboard.insertText(' ')
  await tool(page, 'Base64'); await tool(page, 'JSON')
  await input(page).focus(); await page.keyboard.press('Control+z')
  await input(page).press('Control+Enter'); await complete(page)
  await expect(output(page)).toContainText('你好🌍')
})

test('copy feedback reports success and permission failure', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await go(page, 'json'); await input(page).fill('{"id":9223372036854775807}')
  await page.getByRole('button', { name: '格式化', exact: true }).click(); await complete(page)
  await page.getByRole('button', { name: '复制', exact: true }).click()
  await expect(page.locator('.app-toast')).toContainText('已复制')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('9223372036854775807')
  await page.evaluate(() => { navigator.clipboard.writeText = () => Promise.reject(new DOMException('denied', 'NotAllowedError')) })
  await page.getByRole('button', { name: '复制', exact: true }).click()
  await expect(page.locator('.app-toast')).toContainText('复制失败')
})

test('a cancelled worker cannot replace newer input and processing can resume', async ({ page }) => {
  const blocked = []
  await page.route('**/*processor*', route => { blocked.push(route) })
  await go(page, 'json'); await input(page).fill('{"old":true}')
  await page.getByRole('button', { name: '格式化', exact: true }).click()
  await expect(page.locator('.workspace-status')).toContainText('处理中')
  await page.getByRole('button', { name: '取消处理', exact: true }).click()
  await expect(page.locator('.workspace-status')).toContainText('已取消')
  await input(page).fill('{"new":true}')
  await page.unroute('**/*processor*')
  for (const route of blocked) await route.abort().catch(() => {})
  await page.getByRole('button', { name: '格式化', exact: true }).click(); await complete(page)
  await expect(output(page)).toContainText('new'); await expect(output(page)).not.toContainText('old')
})

test('text operations chain, retain drafts and compare results on both Diff sides', async ({ page }) => {
  await go(page, 'text')
  const text = page.getByRole('textbox', { name: '输入文本', exact: true })
  await text.fill(' beta \nalpha\nbeta')
  await page.getByRole('button', { name: '处理', exact: true }).click(); await complete(page)
  await expect(output(page)).toContainText('beta')
  await page.getByRole('combobox', { name: '发送结果到工具' }).selectOption('diff')
  await expect(page.getByRole('textbox', { name: '原始内容', exact: true })).toContainText('alpha')
  await tool(page, '文本处理')
  await page.getByRole('button', { name: '结果用作输入', exact: true }).click()
  await expect(text).toBeFocused()
  await page.getByRole('combobox', { name: '文本操作' }).selectOption('unique')
  await text.press('Control+Enter'); await complete(page)
  await page.getByRole('button', { name: '结果用作输入', exact: true }).click()
  await page.getByRole('combobox', { name: '文本操作' }).selectOption('sort')
  await page.getByRole('button', { name: '处理', exact: true }).click(); await complete(page)
  await page.getByRole('combobox', { name: '发送结果到工具' }).selectOption('diff:right')
  await expect(page.getByRole('textbox', { name: '原始内容', exact: true })).toContainText('betaalphabeta')
  await expect(page.getByRole('textbox', { name: '修改后内容', exact: true })).toContainText('alphabeta')
  await page.getByRole('button', { name: '比较', exact: true }).click(); await complete(page)
  await expect(page.locator('.diff-block.removed')).toBeVisible()
  await page.getByRole('button', { name: '交换左右', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '原始内容', exact: true })).toContainText('alphabeta')
  await page.locator('#diff-input').getByRole('button', { name: '恢复', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '原始内容', exact: true })).toContainText('betaalphabeta')
})

test('wrapping and cursor survive navigation; maximized input reveals new results', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('dev-tools-layout', 'null'))
  await go(page, 'json')
  await input(page).fill('{"long":"' + 'x'.repeat(200) + '"}')
  await page.locator('#json-input').getByRole('button', { name: '取消换行', exact: true }).click()
  await input(page).press('Control+End')
  await tool(page, 'Base64'); await tool(page, 'JSON')
  await expect(page.locator('#json-input').getByRole('button', { name: '自动换行', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.locator('#json-input .editor-position')).toContainText('第 212 列')
  await page.getByRole('button', { name: '放大输入区', exact: true }).click()
  await page.getByRole('button', { name: '格式化', exact: true }).click(); await complete(page)
  await expect(output(page)).toBeVisible()
  await expect(input(page)).toBeHidden()
})

test('mobile right-side transfer is visible and tabs work with arrow keys', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await go(page, 'json'); await input(page).fill('{"right":true}')
  await page.getByRole('button', { name: '格式化', exact: true }).click(); await complete(page)
  await page.getByRole('combobox', { name: '发送结果到工具' }).selectOption('diff:right')
  await expect(page.getByRole('textbox', { name: '修改后内容', exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: '修改后内容', exact: true })).toContainText('right')
  await expect(page.getByRole('button', { name: '放大结果区', exact: true })).toHaveCount(0)
  await page.getByRole('tab', { name: '修改后内容', exact: true }).focus()
  await page.keyboard.press('ArrowLeft')
  await expect(page.getByRole('textbox', { name: '原始内容', exact: true })).toBeVisible()
  await expect(page.getByRole('tab', { name: '原始内容', exact: true })).toBeFocused()
})

test('Diff applies the same 1 MB import limit on either side', async ({ page }) => {
  await go(page, 'diff')
  const file = { name: 'large.txt', mimeType: 'text/plain', buffer: Buffer.alloc(1024 * 1024 + 1, 'x') }
  await page.getByLabel('导入文本文件', { exact: true }).setInputFiles(file)
  await expect(page.locator('.app-toast')).toContainText('超过 1 MB')
  await page.getByLabel('导入修改后文件', { exact: true }).setInputFiles(file)
  await expect(page.locator('.app-toast')).toContainText('超过 1 MB')
  await expect(page.locator('.workspace-status')).toContainText('0 字符')
})
